services:
  dind:
    image: ghcr.io/manprint/dind-official-full-minimal:${DIND_TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile.minimal
    container_name: dind-env-minimal
    hostname: dind-minimal
    privileged: true
    stdin_open: true
    tty: true
    working_dir: /home/alpine
    environment:
      TZ: Europe/Rome
      LANG: it_IT.UTF-8
      LC_ALL: it_IT.UTF-8
      LANGUAGE: it_IT:it
      HOME: /home/alpine
    volumes:
      - ${DOCKER_DATA:-./data/minimal/docker}:/var/lib/docker
      - ${ALPINE_HOME:-./data/minimal/alpine-home}:/home/alpine
    ports:
      - "2375:2375"
      - "2376:2376"